language: nix

script:
- >
  nix-shell -A idris-patricia                       \
            --command "bash install-dependencies.sh \
                    && idris --testpkg patricia-nix.ipkg --idrispath dependencies/specdris/src"